# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e7e80362ac97767365c958e34e0e9b5f85462117141e7b7485a0522af2be416f7dc198bf1bed81d725877265288cfc028d0ec716c6aab23d07d3e7908a7d121

test:
  secret_key_base: 30f656aa5407c364f29a3654e014f77364d71c89c46bcc9415a1d41295a0e28803f5b37c63766fa689447726ed78f4dc89730dad64e85d94155c970c8c2e89ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
